version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports: 
      - ${DB_PORT}:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PSWD}